### ISSUE TITLE
Fail to compile crate to webassembly

### ISSUE THREAD

**Issue by 573** [kolloch/crate2nix#105]
IDK if that is the right place for my issue, but since my approach is creating webassembly via rust using just nix and crate2nix is involved I would like to ask:

The files I am using as a tiny minimal testbed are src/lib.rs, Cargo.toml and default.nix, see [here for contents pls](https://gist.github.com/573/885a062ca49d2db355c22004cc395066).

I did the following (am in a wsl bash session, should be no problem, should it ?) and still no luck in creating the webassembly code. That I don't understand, why is core compiled by an incompatible version of rustc:

    nix-shell -p wasm-pack cargo rustc -I nixpkgs=channel:nixos-unstable
    cargo generate-lockfile
    crate2nix generate -n '<nixos-unstable>'
    nix-build -I nixpkgs=channel:nixos-unstable
    wasm-pack build --target web

>[INFO]: Checking for the Wasm target...  
Error: wasm32-unknown-unknown target not found in sysroot: "/nix/store/lm64cjp5c5kc772rpmf88q22s8lr2zhi-rustc-1.40.0"  
>  
>Used rustc from the following path: "/nix/store/lm64cjp5c5kc772rpmf88q22s8lr2zhi-rustc-1.40.0/bin/rustc"  
It looks like Rustup is not being used. For non-Rustup setups, the wasm32-unknown-unknown target needs to be installed manually. See   https://rustwasm.github.io/wasm-pack/book/prerequisites/non-rustup-setups.html on how to do this.  

Did exactly that:  

    $(which rustc) --print sysroot
>/nix/store/lm64cjp5c5kc772rpmf88q22s8lr2zhi-rustc-1.40.0

    ls -lr /nix/store/lm64cjp5c5kc772rpmf88q22s8lr2zhi-rustc-1.40.0/lib/rustlib/wasm32-unknown-unknown/
> drwxr-xr-x 1 me me 4096 Dec 16 17:43 lib

    wasm-pack build --target web
>[INFO]: Checking for the Wasm target...  
[INFO]: Compiling to Wasm...  
   Compiling proc-macro2 v1.0.8  
   Compiling unicode-xid v0.2.0  
   Compiling syn v1.0.14  
   Compiling wasm-bindgen-shared v0.2.58  
   Compiling log v0.4.8  
   Compiling cfg-if v0.1.10  
   Compiling bumpalo v3.2.0  
   Compiling lazy_static v1.4.0  
   Compiling wasm-bindgen v0.2.58  
error[E0514]: found crate `core` compiled by an incompatible version of rustc  
  |  
  = help: please recompile that crate using this compiler (rustc 1.40.0)  
  = note: the following crate versions were found:  
          crate `core` compiled by rustc 1.40.0 (73528e339 2019-12-16):   /nix/store/lm64cjp5c5kc772rpmf88q22s8lr2zhi-rustc-1.40.0/lib/rustlib/wasm32-unknown-unknown/lib/libcore-ef54709e300503ed.rlib  
>  
>error: aborting due to previous error  
>  
>error: could not compile `cfg-if`.  
warning: build failed, waiting for other jobs to finish...  
error: build failed  
Error: Compiling your crate to WebAssembly failed  
Caused by: failed to execute `cargo build`: exited with exit code: 101

**Comment by kolloch** [comment]
Not 100% sure what you try to achieve but WASM is currently not a supported target by `crate2nix`.

It is not out-of-scope so I'd appreciate a contribution in that direction (complete with tests and documentation) but I am not sure when I am able to work on it.

Also note that I don't have experience with WASM yet myself, therefore I don't know what wasm-pack is supposed to do.

`nix-build -I nixpkgs=channel:nixos-unstable` will build the project for your current target architecture and probably not WASM. Since your `wasm-pack` invocation does not refer to the build output, I think that it is simply rebuilding your sources from scratch all over. I might miss stuff.

See also https://github.com/kolloch/crate2nix/issues/25

**Comment by kolloch** [comment]
@manveru Maybe you solved the issue for you meanwhile?

**Comment by kolloch** [comment]
I will close this as a duplicate. Continue on #25.

**Comment by 573** [comment]
Thx for the fast response, I'll follow #25 .
I am pretty new to wasm. Think wasm-pack as a good entrypoint to wasm using rust as backend, kind of.
Have no solution ATM.
