### ISSUE TITLE
-Zbuild-std support

### ISSUE THREAD

**Issue by Ericson2314** [kolloch/crate2nix#118]
See https://github.com/rust-lang/wg-cargo-std-aware, it's finally happening that Cargo learns of std, core, and the other libraries today distributed with rstuc, and thus *all* of ones crates. It would be nice crate2nix could support this, they are a natural fit as.

**Comment by kolloch** [comment]
Do I understand correctly, that this is about building std/core from source?

I guess this would need changes in `nixpkgs` and `crate2nix`.

If anyone could sketch out the needed changes, that would be nice to see if there is any downside.

**Comment by Ericson2314** [comment]
I'm not sure. It's possible `-Zbuild-std` makes a different lock file and then it "just works".

**Comment by Ericson2314** [comment]
https://github.com/kolloch/crate2nix/issues/161 Silly me, I opened the same issue twice. I'll keep the second one as that has more info.
