### ISSUE TITLE
Remove unnecessary metadata.

### ISSUE THREAD

**Issue by Profpatsch** [kolloch/crate2nix#12]
Since the file is completely defined by the `Cargo.toml` lock file, we don’t need to add any metadata and should leave all inspection to `cargo`.

**Comment by kolloch** [comment]
Thanks for your comment. Unfortunately, I don't understand exactly what you mean. Which file/metadata do you mean? What do you mean by adding it?

**Comment by Profpatsch** [comment]
It’s probably just the authors field right now:

```
        authors = [
          "a@b.de"
          "Foo <foo@example.com>"
        ];
```

I was thinking about missing a `license` field, but then it occurred to me that the generated nix file is probably not the right place to store this information, when you can also query it with `cargo`'

**Comment by kolloch** [comment]
The metadata is actually used by some builds. E.g. some crates expect the metadata to be available in environment variables in builds and make them available in the version info or similar.

Therefore, for maximum compatibility, I try to keep that metadata.
