### ISSUE TITLE
Cannot compile 'wasm-bindgen-futures' due conditional dependency on target feature

### ISSUE THREAD

**Issue by TheNeikos** [kolloch/crate2nix#136]
I am currently trying to build a crate that as one of its transitive dependencies `wasm-bindgen-futures` and from this code: https://github.com/rustwasm/wasm-bindgen/blob/master/crates/futures/Cargo.toml#L18 it generates the following code:

```
target = { target, features }: (target."feature" == "atomics");
```

This then errors with: `attribute 'feature' missing`.

It is similar to https://github.com/kolloch/crate2nix/issues/37 but it uses `target_feature` here instead of just `target`

**Comment by bbigras** [comment]
I have a similar problem (`target = { target, features }` line):

```nix
      "aes" = rec {
        crateName = "aes";
        version = "0.3.2";
        edition = "2015";
        sha256 = "1j90iwpax0y1dqq14i8y9xgpcnnlgnljwkxg3mhzrralwf7ivssl";
        authors = [
          "RustCrypto Developers"
        ];
        dependencies = [
          {
            name = "aes-soft";
            packageId = "aes-soft";
            target = { target, features }: (!((target."feature" == "aes") && (target."feature" == "sse2") && ((target."arch" == "x86_64") || (target."arch" == "x86"))));
          }
```

**Comment by sireliah** [comment]
Adding a `feature = ""` in `defaultTarget` is a [hotfix](https://github.com/pandaman64/oekaki/blob/master/backend/Cargo.nix.patch) that worked for me.

**Comment by kolloch** [comment]
Merged this https://github.com/kolloch/crate2nix/pull/142

I hope it helps!
