### ISSUE TITLE
Add to nixpkgs?

### ISSUE THREAD

**Issue by Mic92** [kolloch/crate2nix#137]
Is this too early to add it to nixpkgs yet? I thought about replacing carnix in ofborg with it.

**Comment by kolloch** [comment]
No, should be totally fine. 

[as long as you let me update ;)]

We don't break things working in a stable release - at least not on purpose and without a deprecation transition.

**Comment by cole-h** [comment]
It's been a while since this was opened, so I went ahead and packaged crate2nix for Nixpkgs in https://github.com/NixOS/nixpkgs/pull/104027. PTAL!

**Comment by kolloch** [comment]
Thank you, @cole-h :)
