### ISSUE TITLE
Non-existent feature references in `target.cfg(...)` will cause evaluation failures

### ISSUE THREAD

**Issue by nagisa** [kolloch/crate2nix#141]
It is not invalid to have a crate like this:

```toml
# cat Cargo.toml
[package]
name = "wow"
version = "0.1.0"

# Effectively a no-op, however cargo still verifies that the dependency can be resolved
[target.'cfg(banana)'.dependencies]
psm = "0"
```

But when generated with crate2nix and built it will fail:

```
$ crate2nix generate -o Cargo.nix
Generated Cargo.nix successfully.
$ nix build -f Cargo.nix workspaceMembers.wow
error: attribute 'banana' missing, at /tmp/wow/Cargo.nix:117:44
(use '--show-trace' to show detailed location information)
```

A real project with such a problem is [tokio-bytes](https://github.com/tokio-rs/bytes/blob/008d3e508e2247dbfbf5a73918e2fe999a4e9158/Cargo.toml#L33).

cc @jlas

**Comment by Ericson2314** [comment]
I think the remaining issue is this + cross compilation. Because I am getting it with build-time deps.

 of mine for which @nagisa made

**Comment by nagisa** [comment]
Just to clarify, I meant this issue to be an example that there are issues in crate2nix with the `[target.cfg(...).dependencies.cratename]` form of dependency specification. Not necessarily that this issue is the correct one to track the issue that you had with `libloading`. I suspect that the issue might have a slightly different underlying cause (e.g. you mention x-compilation),  and a separate issue is likely in order.
