### ISSUE TITLE
Features fail to contain optional dependencies that got enabled indirectly

### ISSUE THREAD

**Issue by nagisa** [kolloch/crate2nix#146]
Consider the following Cargo.toml:

```toml
[package]
name = "test-num-features"
version = "0.1.0"
edition = "2018"

[dependencies]
num = { version = "=0.3", default-features = false, features = ["std"] }
```

It currently fails to build despite succeeding with cargo. The reason is because when `crate2nix` is building `num-rational` it somehow drops the feature for an optional `num-bigint` dependency. This optional dependency ends up being enabled indirectly, through `num` depending on both `num-rational` and `num-bigint`.

Both `cargo metadata` and the generated `Cargo.nix` contains `num-bigint` in the `resolvedDefaultFeatures`:

```nix
{
      "num-rational" = rec {
        crateName = "num-rational";
        version = "0.3.0";
        edition = "2018";
        sha256 = "0f41j1l1kn5jj36a8xdy8kv242wlwq0ka578vm8gnb1n1wvdgd55";
        authors = [<snip>];
        dependencies = [<snip>];
        buildDependencies = [<snip>];
        features = {
          "default" = [ "num-bigint-std" "std" ];
          "num-bigint-std" = [ "num-bigint/std" ];
          "std" = [ "num-integer/std" "num-traits/std" ];
        };
        resolvedDefaultFeatures = [ "num-bigint" "num-bigint-std" "std" ];
      };
}
```

But the final invocation of `buildRustCrate` ends up not being provided the feature in the end. And so `num-rational` is compiled without a `--cfg feature="num-bigint"` flag.

I admit that this is the first time I’m reading [templates/nix/crate2nix/default.nix](https://github.com/kolloch/crate2nix/blob/master/crate2nix/templates/nix/crate2nix/default.nix) at all seriously, but from what I can tell it just throws away the information `cargo` already computed and attempts to compute its own feature sets. Is that correct? Why?

**Comment by kolloch** [comment]
Hmmm, it is a bit weird because there is even a unit test for something very similar:

https://github.com/kolloch/crate2nix/blob/master/crate2nix/templates/nix/crate2nix/tests/packageFeatures.nix#L98-L104

```nix
 "pkg_num" = {
      crateName = "num";
      dependencies = [
        {
          name = "num-bigint";
          packageId = "pkg_num_bigint";
          usesDefaultFeatures = false;
          optional = true;
        }
      ];
      features = {
        "default" = [ "std" ];
        "std" = [ "num-bigint/std" ];
      };
    };
```

**Comment by pandaman64** [comment]
When Cargo see `num-bigint/std`, it *implicitly* adds `num-bigint` feature to the rustc invocation.
Although the expected feature set in the test matches the explicitly specified ones, it misses implicit features in this case.

For more detail, please see #165.

**Comment by Fuuzetsu** [comment]
Is there any work-around for this or planned work? I am hitting this exact issue on this exact crate.

**Comment by Fuuzetsu** [comment]
For us, I did something like this:

```nix
  cargoNix = pkgs.callPackage ./nix/Cargo.nix {
    inherit nixpkgs;
    buildRustCrate = null;
    defaultCrateOverrides = pkgs.defaultCrateOverrides // {
      num-rational = attrs:
        attrs // {
          # https://github.com/kolloch/crate2nix/issues/146
          features = attrs.features ++ [ "num-bigint" ];
        };
    };
```
