### ISSUE TITLE
Production use (non-local)

### ISSUE THREAD

**Issue by maisiliymBridj** [kolloch/crate2nix#148]
Obviously, forking every repo to add a Cargo.nix file is absurd, and nixpkgs never took that approach. Rather, the source is treated as unalterable, patched in the worst case, and given as an argument to a builder. But after looking through the source and GH issues, there is no indication that it is possible to use crate2nix this way.
`crate2nix generate -f https://github.com/kolloch/crate2nix -o ~/wrapperNixFlake/cargo.nix` ??

**Comment by AluisioASG** [comment]
I think what you want are [out-of-tree](https://github.com/kolloch/crate2nix/blob/7820ab241662009b35d081ceec7e9976ae17270a/out-of-tree-sources.md) sources? Then you can either `nix-build Cargo.nix -A myPackage` or [override](https://git.sr.ht/~aasg/nixexprs/tree/7122fd82/pkgs/servers/dns/trust-dns/default.nix) it with metadata.

**Comment by xcthulhu** [comment]
[Last year](https://github.com/kolloch/crate2nix/issues/8#issuecomment-509225520) I suggested that `crate2nix` ship with a nix-function similar to [`callCabal2nix`](https://github.com/NixOS/nixpkgs/blob/4abb8be7abec422bb221816931148d9465e380f3/pkgs/development/haskell-modules/make-package-set.nix#L173-L188) which wraps [`cabal2nix`](https://github.com/NixOS/cabal2nix), or [`mkYarnPackage`](https://github.com/nix-community/yarn2nix#yarn2nix) which wraps `yarn2nix`.

Here's a prototype that tries to build [`websocat`](https://github.com/vi/websocat):

```nix
{ pkgs ? import <nixpkgs> { }, rustPlatform ? pkgs.rustPlatform }:
let
  crate2nix = (pkgs.callPackage (pkgs.fetchFromGitHub {
    owner = "kolloch";
    repo = "crate2nix";
    rev = "7820ab241662009b35d081ceec7e9976ae17270a";
    sha256 = "09psd9jnjwpqlrdysvzspxp1b7kf2mv5dbaryhi03wxh3yzzmj46";
  }) { });

  callCrate2nix = { src }: pkgs.stdenv.mkDerivation ({
    name = "default.nix";

    buildCommand = ''
    # crate2nix needs to open Cargo.lock with write permissions
    # chmod u+w ${src}/Cargo.lock
    ${crate2nix}/bin/crate2nix generate -f ${src}/Cargo.toml -o $out
    '';
  });

  src = pkgs.fetchFromGitHub {
    owner = "vi";
    repo = "websocat";
    rev = "af92843e27932077abdfbfc192c0d483f4a53cc4";
    sha256 =  "0iilq96bxcb2fsljvlgy47pg514w0jf72ckz39yy3k0gwc1yfcja";
  };

  project = callCrate2nix { inherit src; };

in (pkgs.callPackage project {}).rootCrate.build
```

However, since I originally posted `crate2nix` has stopped working offline. It appears it tries to fetch https://github.com/rust-lang/crates.io-index now and fails because nix builds are denied network access.

@kolloch are you still interested in supporting something like `callCrate2nix`?  Might not be too hard to get it to work offline...

**Comment by balsoft** [comment]
@xcthulhu I am very much interested in this, however I'm quite new to Rust world (coming from the Nix side of things). Would you have any suggestions on an approach to fixing this?

**Comment by xcthulhu** [comment]
@balsoft When I write that derivation to a `default.nix` and run it, I bump into this error:

```
nix-shell
building '/nix/store/nk8k1jla4vh1d8kvcdqq9w4hrwcb4ahb-default.nix.drv'...
Error: while retrieving metadata about /nix/store/bk5xz0spch2x280awp7gqj58f29r6h0g-source/Cargo.toml: Error during execution of `cargo metadata`:     Updating crates.io index
warning: spurious network error (2 tries remaining): [6] Couldn't resolve host name; class=Net (12)
warning: spurious network error (1 tries remaining): [6] Couldn't resolve host name; class=Net (12)
error: failed to fetch `https://github.com/rust-lang/crates.io-index`
```

I've tried having `crate2nix` run `cargo metadata --offline`, but it still needs a copy of the registry to continue.

A local registry could be specified in a `config.toml` file, which could in turn be specified with the command:

```
cargo +nightly metadata -Z unstable-options -Zconfig-include --config config.toml --offline
``` 

So the steps we could take are:

1. Use a derivation to fetch `https://github.com/rust-lang/crates.io-index` so it can be used as a local repository.  The `callCrate2Nix` function I have suggested could even take a pinned version of this as an optional argument.

2. Generate a custom `config.toml`.  This would point to a local repository in `/nix` from the `crates.io-index` repository.  Unfortunately this needs the name of the crate being built, which can be parsed from the `Cargo.toml` file.  Not sure if this can be done in `nix` alone.

3. Modify `crate2nix` to take an `--offline` argument and a `--config` argument.  We'd then adjust the `crate2nix` function to use these arguments.

I am not sure about step 2, I will try to experiment with this further.

**Comment by balsoft** [comment]
Thanks for the investigation!

> Generate a custom config.toml. This would point to a local repository in /nix from the crates.io-index repository. Unfortunately this needs the name of the crate being built, which can be parsed from the Cargo.toml file. Not sure if this can be done in nix alone.

Nix has `builtins.fromTOML` since at least 2.0, so this should be really simple. Generating TOML-style files is simple too: `nixpkgs.lib.generators.toINI` . In general, I think this is indeed pretty easy.

**Comment by balsoft** [comment]
A WIP PR is #151

**Comment by danieldk** [comment]
> Obviously, forking every repo to add a Cargo.nix file is absurd, and nixpkgs never took that approach. Rather, the source is treated as unalterable, patched in the worst case, and given as an argument to a builder. But after looking through the source and GH issues, there is no indication that it is possible to use crate2nix this way.
> `crate2nix generate -f https://github.com/kolloch/crate2nix -o ~/wrapperNixFlake/cargo.nix` ??

If you do not want to use IFD or anything fancy, you can just use

```
crate2nix generate -o Cargo.nix
```

and then do something like the following:

https://github.com/stickeritis/nix-packages/tree/624d472cc83e75f05c9d42087f32adda3a676327/pkgs/sticker2

The `Cargo.nix` file is just the file generated using `crate2nix` unaltered and this is then used by `default.nix`.

**Comment by danieldk** [comment]
> @kolloch are you still interested in supporting something like `callCrate2nix`? Might not be too hard to get it to work offline...

See `tools.nix`. I have been using this in CI in some projects to avoid having to recreate `Cargo.nix` manually. E.g.:

https://github.com/stickeritis/sticker2/blob/b1a9547bfcd37570cd364a832d28d1944b7da062/tests.nix

**Comment by xcthulhu** [comment]
@danieldk I see now... @kolloch mentioned `tools.nix` in https://github.com/kolloch/crate2nix/pull/151

@maisiliymBridj To answer your original issue, here's an example of how you could use `tools.nix` to make a derivation for [`websocat`](https://github.com/vi/websocat):

```nix
{ pkgs ? import <nixpkgs> { } }:
let
  crate2nix-tools = import "${
      builtins.fetchGit {
        url = "git@github.com:kolloch/crate2nix.git";
        ref = "master";
        rev = "e07af104b8e41d1cd7e41dc7ac3fdcdf4953efae";
      }
    }/tools.nix" { };
  project = pkgs.callPackage (crate2nix-tools.generatedCargoNix {
    name = "websocat";
    src = builtins.fetchTarball
      "https://github.com/vi/websocat/archive/master.tar.gz";
  }) { };
in project.rootCrate.build
```

**Comment by maisiliymBridj** [comment]
> ```nix
> { pkgs ? import <nixpkgs> { } }:
> let
>   crate2nix-tools = import "${
>       builtins.fetchGit {
>         url = "git@github.com:kolloch/crate2nix.git";
>         ref = "master";
>         rev = "e07af104b8e41d1cd7e41dc7ac3fdcdf4953efae";
>       }
>     }/tools.nix" { };
>   project = pkgs.callPackage (crate2nix-tools.generatedCargoNix {
>     name = "websocat";
>     src = builtins.fetchTarball
>       "https://github.com/vi/websocat/archive/master.tar.gz";
>   }) { };
> in project.rootCrate.build
> ```

That's impure. Nix 3.0 kicks impurity in the balls and lets it choke on its vomit, which is great!

Thanks @AluisioASG , that helps.

Given theres #102, this is a duplicate, closing.
