### ISSUE TITLE
note: ld: file not found: /usr/lib/system/libcache.dylib for architecture x86_64

### ISSUE THREAD

**Issue by PlumpMath** [kolloch/crate2nix#156]
building '/nix/store/qhvr89l0ripvfnngl9lvnf3ccxv5308r-rust_bitflags-1.2.1.drv'...
unpacking sources
unpacking source archive /nix/store/s8x3gwl0y2a5j4ihxpnnzzpl1v0c9vvi-bitflags-1.2.1.tar.gz
source root is bitflags-1.2.1
setting SOURCE_DATE_EPOCH to timestamp 1571008866 of file bitflags-1.2.1/src/lib.rs
patching sources
configuring
Running cd .
Building build.rs (bitflags)
Running rustc --crate-name build_script_build build.rs --crate-type bin -C opt-level=3 -C codegen-units=16 --edition 2015 --cfg feature="default" --out-dir target/build/bitflags --emit=dep-info,link -L dependency=target/buildDeps --cap-lints allow --color always
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-m64" "-arch" "x86_64" "-L" "/nix/store/phal6w0ysmli7glprn0gjqcshp6k48rs-rust-1.48.0-2020-11-16-7eac88abb/lib/rustlib/x86_64-apple-darwin/lib" "target/build/bitflags/build_script_build.build_script_build.7rcbfp3g-cgu.0.rcgu.o" "target/build/bitflags/build_script_build.build_script_build.7rcbfp3g-cgu.1.rcgu.o" "target/build/bitflags/build_script_build.build_script_build.7rcbfp3g-cgu.10.rcgu.o" "target/build/bitflags/build_script_build.build_script_build.7rcbfp3g-cgu.11.rcgu.o" "target/build/bitflags/build_script_build.build_script_build.7rcbfp3g-cgu.12.rcgu.o" "target/build/bitflags/build_script_build.build_script_build.7rcbfp3g-cgu.13.rcgu.o" "target/build/bitflags/build_script_build.build_script_build.7rcbfp3g-cgu.14.rcgu.o" "target/build/bitflags/build_script_build.build_script_build.7rcbfp3g-cgu.15.rcgu.o" "target/build/bitflags/build_script_build.build_script_build.7rcbfp3g-cgu.2.rcgu.o" "target/build/bitflags/build_script_build.build_script_build.7rcbfp3g-cgu.3.rcgu.o" "target/build/bitflags/build_script_build.build_script_build.7rcbfp3g-cgu.4.rcgu.o" "target/build/bitflags/build_script_build.build_script_build.7rcbfp3g-cgu.5.rcgu.o" "target/build/bitflags/build_script_build.build_script_build.7rcbfp3g-cgu.6.rcgu.o" "target/build/bitflags/build_script_build.build_script_build.7rcbfp3g-cgu.7.rcgu.o" "target/build/bitflags/build_script_build.build_script_build.7rcbfp3g-cgu.8.rcgu.o" "target/build/bitflags/build_script_build.build_script_build.7rcbfp3g-cgu.9.rcgu.o" "-o" "target/build/bitflags/build_script_build" "target/build/bitflags/build_script_build.1enide7h7a8vrbgy.rcgu.o" "-Wl,-dead_strip" "-nodefaultlibs" "-L" "target/buildDeps" "-L" "/nix/store/phal6w0ysmli7glprn0gjqcshp6k48rs-rust-1.48.0-2020-11-16-7eac88abb/lib/rustlib/x86_64-apple-darwin/lib" "/nix/store/xv3jxi6arx6zaw3b9db66d5rbql8k8lb-rust/lib/rustlib/x86_64-apple-darwin/lib/libstd-688c1376a25c049d.rlib" "/nix/store/xv3jxi6arx6zaw3b9db66d5rbql8k8lb-rust/lib/rustlib/x86_64-apple-darwin/lib/libpanic_unwind-078f89c2cdb6d46b.rlib" "/nix/store/xv3jxi6arx6zaw3b9db66d5rbql8k8lb-rust/lib/rustlib/x86_64-apple-darwin/lib/libobject-fec020208bc1ad3c.rlib" "/nix/store/xv3jxi6arx6zaw3b9db66d5rbql8k8lb-rust/lib/rustlib/x86_64-apple-darwin/lib/libaddr2line-38540dcacc9fd218.rlib" "/nix/store/xv3jxi6arx6zaw3b9db66d5rbql8k8lb-rust/lib/rustlib/x86_64-apple-darwin/lib/libgimli-6f613179f618c598.rlib" "/nix/store/xv3jxi6arx6zaw3b9db66d5rbql8k8lb-rust/lib/rustlib/x86_64-apple-darwin/lib/librustc_demangle-4d1a5d7118aaeaf2.rlib" "/nix/store/xv3jxi6arx6zaw3b9db66d5rbql8k8lb-rust/lib/rustlib/x86_64-apple-darwin/lib/libhashbrown-d88fab3b1b9d8356.rlib" "/nix/store/xv3jxi6arx6zaw3b9db66d5rbql8k8lb-rust/lib/rustlib/x86_64-apple-darwin/lib/librustc_std_workspace_alloc-a21754532a052f2f.rlib" "/nix/store/xv3jxi6arx6zaw3b9db66d5rbql8k8lb-rust/lib/rustlib/x86_64-apple-darwin/lib/libunwind-2e9ebc4127641a96.rlib" "/nix/store/xv3jxi6arx6zaw3b9db66d5rbql8k8lb-rust/lib/rustlib/x86_64-apple-darwin/lib/libcfg_if-82d0f961232a05ca.rlib" "/nix/store/xv3jxi6arx6zaw3b9db66d5rbql8k8lb-rust/lib/rustlib/x86_64-apple-darwin/lib/liblibc-370b1b71f08bac3c.rlib" "/nix/store/xv3jxi6arx6zaw3b9db66d5rbql8k8lb-rust/lib/rustlib/x86_64-apple-darwin/lib/liballoc-816106c1f35f5421.rlib" "/nix/store/xv3jxi6arx6zaw3b9db66d5rbql8k8lb-rust/lib/rustlib/x86_64-apple-darwin/lib/librustc_std_workspace_core-20f3a030f1a56a86.rlib" "/nix/store/xv3jxi6arx6zaw3b9db66d5rbql8k8lb-rust/lib/rustlib/x86_64-apple-darwin/lib/libcore-60333aa00936c5ce.rlib" "/nix/store/xv3jxi6arx6zaw3b9db66d5rbql8k8lb-rust/lib/rustlib/x86_64-apple-darwin/lib/libcompiler_builtins-116aaeaea873ef94.rlib" "-lSystem" "-lresolv" "-lc" "-lm"
  = note: ld: file not found: /usr/lib/system/libcache.dylib for architecture x86_64
          clang-7: error: linker command failed with exit code 1 (use -v to see invocation)
          

error: aborting due to previous error

builder for '/nix/store/qhvr89l0ripvfnngl9lvnf3ccxv5308r-rust_bitflags-1.2.1.drv' failed with exit code 1
cannot build derivation '/nix/store/1fg1grca3mwrlbmkr3xwi740p50iqdc5-rust_crate2nix-0.8.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/p12s2gxgnd5qv792hpc7pbih381fq0k3-rust_crate2nix-0.8.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/w9al2cqirmha3al38n6jjx0zar2780ma-pnix.drv': 1 dependencies couldn't be built
error: build of '/nix/store/w9al2cqirmha3al38n6jjx0zar2780ma-pnix.drv' failed

**Comment by PlumpMath** [comment]
I installed rust after updating to macos big sur, but crate2nix cannot be installed.

**Comment by PlumpMath** [comment]
Solve.
 Change nix-channel to nixpkgs-unstable.
.
Maybe fixes nix-darwin 아저씨가...
.
Change nix-channel to "nixpkgs-unstable"

nix-channel --add ~~~nixpkgs-unstable nixpkgs
nix-channel --update
nix-env -u

And update.

**Comment by kolloch** [comment]
Thank you so much, for coming back with the solution as well, @PlumpMath! I don't have access to a computer with Big Sur...
