### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by symphorien** [kolloch/crate2nix#164]
It has been nearly a year and no new release of crate2nix is out. nixpkgs now has a one year old crate2nix :( I'm selfishly waiting for https://github.com/kolloch/crate2nix/pull/123 to be fixed in nixpkgs.

**Comment by zseri** [comment]
I also ran into this in https://github.com/kolloch/crate2nix/issues/168

**Comment by P-E-Meunier** [comment]
@zseri's comment means my CI is broken :(

**Comment by kolloch** [comment]
Valid point! On it :)

**Comment by kolloch** [comment]
I released 0.9.0

**Comment by kolloch** [comment]
https://github.com/kolloch/crate2nix/releases/tag/v0.9.0

**Comment by P-E-Meunier** [comment]
Thanks!
