### ISSUE TITLE
[nitpick] Prevent emitting of trailing whitespace

### ISSUE THREAD

**Issue by zseri** [kolloch/crate2nix#167]
Some lines of the produced `Cargo.nix` file in multiple crates I either use or manage contain lines which either have trailing space characters (` `) or consist solely of spaces.

**Comment by zseri** [comment]
The fix seems to be almost good enough, but some regenerated `Cargo.nix` files seem to have no trailing newline. Additionally, some `Cargo.nix` files now have a leading newline.

**Comment by kolloch** [comment]
Yeah, never understood this trailing newline business. Seems redundant, why do tools screem about it?

**Comment by zseri** [comment]
Nah, in many editors (e.g. `nano`) it's extremely annoying to not have a trailing newline, if the last line is long, as it is not trivial to insert a line after it.

**Comment by kolloch** [comment]
Wow, that seems quite broken.

Even if trailing newlines are a problem somewhere, especially editors should be able to fix that.

I personally never encountered problems with trailing spaces or missing trailing newlines except that some tools show them and complain.

That said, it is really easy to fix in `crate2nix` so if it helps you or others...
