### ISSUE TITLE
Difference in behaviour of `include_str` in a workspace

### ISSUE THREAD

**Issue by tilpner** [kolloch/crate2nix#17]
[Test case is here](https://github.com/tilpner/crate2nix-testcases/tree/master/include).

This project compiles with cargo build, but not with crate2nix.

Including files from the same workspace but not the same crate is probably a niche feature (if it even is feature! I don't know if this is intentionally allowed by cargo, or was just forgotten to forbid).

I would understand a choice not to support this, but I brought it up anyway in case you want to fix all differences from the build process of cargo.

**Comment by kolloch** [comment]
I'll think about this. Thank you for reporting it and the test case!

**Comment by kolloch** [comment]
I closed this as I consider this WAI.

**Comment by noverby** [comment]
@kolloch How can you workaround this limitation, if you have shared files in a workspace (E.g schemas)?
