### ISSUE TITLE
Can't build crate with dependency num 0.4.0

### ISSUE THREAD

**Issue by 1000teslas** [kolloch/crate2nix#182]
I get this error
```
error[E0432]: unresolved import `num_rational::BigRational`
  --> src/lib.rs:68:9
   |
68 | pub use num_rational::BigRational;
   |         ^^^^^^^^^^^^^^-----------
   |         |             |
   |         |             help: a similar name exists in the module: `Rational`
   |         no `BigRational` in the root
```
when trying to `nix-build` the generated `Cargo.nix`. However `cargo build` works fine.

**Comment by pandaman64** [comment]
Dupe of #146

**Comment by kolloch** [comment]
Hey @1000teslas,

thank you so much for reporting this! 

@pandaman64 has fixed this in a recent PR. Would you help by retesting it with the master version?

Thank you.

**Comment by 1000teslas** [comment]
seems like it works fine. thanks.

**Comment by kolloch** [comment]
Awesome, thanks for getting back to us!

**Comment by bbigras** [comment]
I had the same problem and master also fixed it. Thanks for the quick fix!
