### ISSUE TITLE
Dependency on `rand = "0.7"` fails

### ISSUE THREAD

**Issue by TMVector** [kolloch/crate2nix#20]
I get an error when building with nix if my package depends on the `rand` package at version `0.7`. There doesn't seem to be an issue with the previous version `0.6.5`.

I am using the version of nixpkgs you have pinned (`a2e219ec879fe3de62e9204ad33efb5b67a4a324`).

**Cargo.toml**
```toml
[package]
name = "t"
version = "0.1.0"
edition = "2018"

[dependencies]
rand = "0.7"
```

<details><summary><b>Output</b></summary>

```
$ crate2nix generate && nix-build Cargo.nix -A rootCrate --arg pkgs 'import ./nixpkgs.nix {config={};}'
Prefetching    1/10: https://crates.io/api/v1/crates/c2-chacha/0.2.2/download
Prefetching    2/10: https://crates.io/api/v1/crates/cfg-if/0.1.9/download
Prefetching    3/10: https://crates.io/api/v1/crates/getrandom/0.1.11/download
Prefetching    4/10: https://crates.io/api/v1/crates/lazy_static/1.4.0/download
Prefetching    5/10: https://crates.io/api/v1/crates/ppv-lite86/0.2.5/download
Prefetching    6/10: https://crates.io/api/v1/crates/rand/0.7.0/download
Prefetching    7/10: https://crates.io/api/v1/crates/rand_chacha/0.2.1/download
Prefetching    8/10: https://crates.io/api/v1/crates/rand_core/0.5.1/download
Prefetching    9/10: https://crates.io/api/v1/crates/rand_hc/0.2.0/download
Prefetching   10/10: https://crates.io/api/v1/crates/wasi/0.5.0/download
Wrote hashes to ./crate-hashes.json.
Generated ./Cargo.nix successfully.
these derivations will be built:
  /nix/store/hsagy1dw82qssz23vdj9rngznznjblmm-rust_rand-0.7.0.drv
  /nix/store/ymmq9lhhp5lj4k5161bdach7z0b5xgyl-rust_t-0.1.0.drv
building '/nix/store/hsagy1dw82qssz23vdj9rngznznjblmm-rust_rand-0.7.0.drv'...
unpacking sources
unpacking source archive /nix/store/g8rs43fnnzq9ibv60qwi81f8d1vpwymj-rand-0.7.0.tar.gz
source root is rand-0.7.0.tar.gz
patching sources
configuring
building
Building src/lib.rs (rand)
Running rustc --crate-name rand src/lib.rs --crate-type lib -C opt-level=3 -C codegen-units=12 --edition 2018 -C metadata=f43f81b124 -C extra-filename=-f43f81b124 --cfg feature="alloc" --cfg feature="default" --cfg feature="getrandom" --cfg feature="getrandom_package" --cfg feature="rand_core/alloc" --cfg feature="rand_core/getrandom" --cfg feature="rand_core/std" --cfg feature="std" --out-dir target/lib --emit=dep-info,link -L dependency=target/deps --extern getrandom=/nix/store/61f6yqaaqckc5w30q2cfsvavgma5w5f9-rust_getrandom-0.1.11/lib/libgetrandom-b39e9273b9.rlib --extern libc=/nix/store/l5r0rvqhmhd16r191xks6wfgyqhz5lam-rust_libc-0.2.62/lib/liblibc-efa9f5b24f.rlib --extern rand_chacha=/nix/store/phvgnjvy2w2m3cnmnlwsvbik08w7fwf0-rust_rand_chacha-0.2.1/lib/librand_chacha-7f7ab7e140.rlib --extern rand_core=/nix/store/gpwiabvl10c9hksaxmv9c49gx2i8plga-rust_rand_core-0.5.1/lib/librand_core-ebabdf2568.rlib --cap-lints allow --color always
error[E0432]: unresolved import `getrandom_package`
  --> src/lib.rs:60:5
   |
60 | use getrandom_package as getrandom;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `getrandom_package` external crate

error[E0423]: expected function, found module `getrandom`
  --> src/rngs/os.rs:78:9
   |
78 |         getrandom(dest)?;
   |         ^^^^^^^^^ not a function
help: possible better candidates are found in other modules, you can import them into scope
   |
12 | use getrandom::getrandom;
   |
12 | use libc::getrandom;
   |

error: aborting due to 2 previous errors

Some errors occurred: E0423, E0432.
For more information about an error, try `rustc --explain E0423`.
builder for '/nix/store/hsagy1dw82qssz23vdj9rngznznjblmm-rust_rand-0.7.0.drv' failed with exit code 1
cannot build derivation '/nix/store/ymmq9lhhp5lj4k5161bdach7z0b5xgyl-rust_t-0.1.0.drv': 1 dependencies couldn't be built
error: build of '/nix/store/ymmq9lhhp5lj4k5161bdach7z0b5xgyl-rust_t-0.1.0.drv' failed
```

</details>

---

In particular, [rand@f3e6c75](https://github.com/rust-random/rand/commit/f3e6c75c68d0bd5330e9e75cf3e6399d546575bf) (which seems to be the 0.7 release?) builds okay with cargo but fails to build in nix with `crate2nix` with the same error message. However, master seems to build fine. :thinking:

FYI I am consuming `rand` as a transitive dependency of [`prost-build`](https://github.com/danburkert/prost/blob/v0.5.0/prost-build/Cargo.toml) from `prost`.

---

Thanks for contributing to Rust in nix btw :hugs:

**Comment by gilligan** [comment]
You are experiencing the same issue that i am having: https://github.com/kolloch/crate2nix/issues/19

**Comment by TMVector** [comment]
Thanks @gilligan.

Looking a bit closer (at `cargo metadata` output) I think my issue arises from _package renaming_ in the `getrandom` package, which is [explicitly not supported yet](https://github.com/kolloch/crate2nix#known-restrictions). Whoops.

@gilligan I don't know about the `miniz_oxide` crate being missing, but it looks like you would hit the `getrandom` renaming problem afterwards anyways :confused:.

**Comment by TMVector** [comment]
I guess I should close this issue since it's officially not supported yet.

**Comment by gilligan** [comment]
Can you briefly explain what is going on so i can understand it as well?
What is being renamed?

**Comment by TMVector** [comment]
Sure! I started having a closer look at crate2nix, hoping I could submit a PR, and saw the helpful [list of phases](https://github.com/kolloch/crate2nix#project-overview--terminology), starting with getting metadata from cargo. So I looked at the `cargo metadata` output for the rand crate (I checked out the [source](https://github.com/rust-random/rand/tree/rand_distr-0.2.1), idk if you can do it otherwise).
```
cargo metadata | jq -C . | less -R
```
The error was related to `getrandom_package`, so I searched for that and saw it was actually `getrandom`, renamed! :thinking:

Indeed, looking in the `Cargo.toml`, there is a [line](https://github.com/rust-random/rand/blob/rand_distr-0.2.1/Cargo.toml#L60) which [renames](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#renaming-dependencies-in-cargotoml) `getrandom` `0.1.1` to `getrandom_package`. Tbh I don't really understand what's going on in the cargo file in full, something about making `getrandom` a feature, but this seems to be the source of the problem.

**Comment by kolloch** [comment]
@TMVector Thanks a lot for reporting this, despite this being officially not being supported.

This makes it more visible what people are struggling with. I created an issue for this #22. Help is appreciated. How can we make this work on the nix level?
