### ISSUE TITLE
export: `CARGO_FEATURE_DEP:LAZY_STATIC=1': not a valid identifier

### ISSUE THREAD

**Issue by bbigras** [kolloch/crate2nix#222]
crate2nix 0.10.0

```
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/rllys9szh8pnhlkwggwflhh2kz0kk77h-crossbeam-utils-0.8.7.tar.gz
source root is crossbeam-utils-0.8.7
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
Running cd .
Building build.rs (crossbeam-utils)
Running rustc --crate-name build_script_build build.rs --crate-type bin -C opt-level=3 -C codegen-units=4 --edition 2018 --cfg feature="default" --cfg feature="dep:lazy_static" --cfg feature="lazy_static" --cfg f>
/nix/store/vhdfrizjvb4p58wkidl8hmn5gnp9zbxv-stdenv-linux/setup: line 1516: export: `CARGO_FEATURE_DEP:LAZY_STATIC=1': not a valid identifier
```

**Comment by ben0x539** [comment]
cargo doesnt seem to include `dep:` features in either the CARGO_FEATURE_FOO env vars or the rustc commandline does it

**Comment by JJJollyjim** [comment]
I implemented a fix, using env commands to escape the colons: https://github.com/JJJollyjim/nixpkgs/commit/051ed25169aeea412d795cb62d8a4f19859d9415

However, if @ben0x539 is correct, I guess we should filter them out instead?

**Comment by Fuuzetsu** [comment]
This is now a much bigger concer since Rust 1.60 is out

**Comment by PlumpMath** [comment]
export: `CARGO_FEATURE_DEP:QUOTE=1': not a valid identifier
nixpkgs; I hope it gets fixed soon.

**Comment by teozkr** [comment]
This seems to have been fixed by https://github.com/NixOS/nixpkgs/pull/168865, and shouldn't require any further action here.

**Comment by Ericson2314** [comment]
Glad it is fixed. Thanks @duxovni!
