### ISSUE TITLE
Environment variables not accessible in build script.

### ISSUE THREAD

**Issue by asfishman** [kolloch/crate2nix#26]
I have a packages that specifies a build script called `build.rs` that I am using to create the CFFI. I think that the environment variable `CARGO_MANIFEST_DIR` is not properly set during nix buildtime, as I get the error message: `'main' panicked at 'Unable to generate C bindings.: CargoMetadata("/build/traj/Cargo.toml", Io(Os { code: 2, kind: NotFound, message: "No such file or directory" }))', src/libcore/result.rs:999:5`

**Comment by kolloch** [comment]
@asfishman Thank you for your report! Do you have a complete example? 

`crate2nix` uses `buildRustCrate` from NixOS. `CARGO_MANIFEST_DIR` is set [here](https://github.com/NixOS/nixpkgs/blob/master/pkgs/build-support/rust/build-rust-crate/configure-crate.nix#L86). Do you suspect that `crate2nix` could generate a different nix build file which would result in a correct build or is the error in `buildRustCrate`?

**Comment by asfishman** [comment]
Upon further diving into the code, I see that the environment variable is indeed set. I think that I have determined the issue lies in `cbindgen` and not in the way that nix generates my packages.

That being said, the package builds fine with `cargo`, but fails with `crate2nix`.

**Comment by kolloch** [comment]
Can you supply your `Cargo.toml` and `Cargo.lock` or your whole repository? Whatever is necessary to debug the problem?

Maybe we have to set the environment variables to a different value.

**Comment by asfishman** [comment]
I think there is still an issue here, but unfortunately I do not have time to work on it or debug it further. I may revisit in the coming months.
