### ISSUE TITLE
Git depenency only work for default (master) branch

### ISSUE THREAD

**Issue by andir** [kolloch/crate2nix#27]
When using a git source (e.g. from a fork of an upstream repository because your changes haven't been merged yet) builds done with crate2nix fail since they can't find the git dependency.

This might not really be a bug in `crate2nix` but rather in `builtins.fetchGit`. As it turned out I can fetch the revision from my fork as soon as the commit is in the default (master) branch.

I did expect `crate2nix` to prefetch the repository and the respective commit while generating the `Cargo.nix` file.

**Comment by kolloch** [comment]
Maybe you can try to change the generated output slightly, especially the parameters from `builtins.fetchGit`? If you can make it work with that, please write about your changes here and I make it work with crate2nix.

Thank you!

**Comment by andir** [comment]
In my case I only specified the branch on my Cargo.toml:

```toml
[dependencies.multicast_dns]
version = "0.4.2"
git = "https://github.com/andir/multicast-dns"
branch = "support-announce"
```

Which translated to the following entry in the lock file carrying the revision **AND** branch.

```toml
[[package]]
name = "multicast_dns"
version = "0.4.2"                                                          
source = "git+https://github.com/andir/multicast-dns?branch=support-announce#55d5ade735641a46ee4ce749698a35a6f29cd093"
dependencies = [
 "libc 0.2.62 (registry+https://github.com/rust-lang/crates.io-index)",
 "log 0.4.8 (registry+https://github.com/rust-lang/crates.io-index)",
]
```

So the information seems to be retained. Passing `ref` (branch name/tag) to `builtins.fetchGit` should fix the above error. Does `crate2nix` have that kind of information or do we have to patch the cargo metadata feature?
