### ISSUE TITLE
crate2nix ignores crate-type

### ISSUE THREAD

**Issue by asfishman** [kolloch/crate2nix#31]
The `Cargo.nix` generated by `crate2nix` does not respect the `Cargo.toml` field specifying the crate build type. For example, if the `Cargo.toml` contains the following information:

    [lib]
    crate-type = ["rlib", "staticlib"]

There will be no difference in the `Cargo.nix` output that reflects our desire to build a statically linkable library. Furthermore, the rustc command executed by `buildRustCrate` will not include the desired flags `--crate-type lib --crate-type staticlib`.

The rust machinery in `nixpkgs` already supports this functionality. It just looks like crate2nix does not. I have identified what needs to be added to `Cargo.nix` in order to change this. A crate set just needs to have the attribute `type` which is a list containing one or more of the following strings: 

    bin  lib  rlib  dylib  cdylib  staticlib  proc-macro

If there is no `crate-type` in the `Cargo.toml`, then the `type` attribute of the crate object in `Cargo.nix` should not exist. I manually added this `type` attribute with the appropriate values, and my desired output was achieved.

I have no familiarity with how crate2nix works, so I do not think I will be able to make this feature addition. Hopefully this issue provides sufficient information to make this modification to crate2nix.

**Comment by asfishman** [comment]
I was able to write a quick fix for this. Appreciate feedback:

https://github.com/kolloch/crate2nix/pull/32

**Comment by andir** [comment]
I ran into this as well.
In case someone else needs a workaround for this issue: Simply add the `types` attribute to your crate overrides and it should work (tm).

**Comment by kolloch** [comment]
This was hopefully fixed for lib crate types in #67.

There was already special casing for proc-macros.
