### ISSUE TITLE
Git submodules missing / Switch to pkgs.fetchgit

### ISSUE THREAD

**Issue by andir** [kolloch/crate2nix#34]
When using a git source for a crate the git submodules are not being fetched. This is a limitation of `builtins.fetchGit`. By using `pkgs.fetchgit` one can fetch those but is then required to provide the output hash of the source archive.

In the long run it is probably best to just do something like `nix-prefetch-git` for all of the git crates and always use `pkgs.fetchgit` (or even `pkgs.fetchFromGitHub` where possible).

This would also aid generating expressions that can be built in pure mode. For example on hydra instances.

**Comment by kolloch** [comment]
I'd love to avoid prefetching as much as possible. Is there a chance to auto-detect submodules somehow? Probably not because you have to fetch the git repository to know if it contains sub modules?

**Comment by andir** [comment]
> I'd love to avoid prefetching as much as possible. Is there a chance to auto-detect submodules somehow? Probably not because you have to fetch the git repository to know if it contains sub modules?

Yeah, you are probably right. There is no correct way to predict that.

What is the problem you are trying to avoid with prefetching?
I would like to avoid the extra complexity but in the long run that might not really be feasible.

**Comment by cpcloud** [comment]
I'm working on this and will have a PR up tomorrow. I've got cloning working, but I can't seem to figure out how to get my test to pick up the submodule's path. I'm currently trying to use `crateOverrides` but that doesn't seem to solve the problem.
