### ISSUE TITLE
Cannot generate the `with_problematic_crates` Cargo.nix sample

### ISSUE THREAD

**Issue by nlewo** [kolloch/crate2nix#36]
I'm trying to (re)generate the `Cargo.nix` file from the sample project `with_problematic_crates` but my `crate2nix` doesn't generate the same file (`libPath` attributes are missing for instance)

Here are the commands I executed:
```
[lewo@tilia:~/repos/crate2nix]$ git log -n1 --oneline 
277fe73 (HEAD -> master, origin/master) Fix #23 - Move integration tests into nix

[lewo@tilia:~/repos/crate2nix]$ nix-shell
crate2nix 0.6.0-alpha.0
Peter Kolloch <info@eigenvalue.net>
Nix build file generator for a cargo rust projects.

USAGE:
    crate2nix <SUBCOMMAND>

FLAGS:
    -h, --help       Prints help information
    -V, --version    Prints version information

SUBCOMMANDS:
    completions    Generate auto-completions for the shell.
    generate       Generate a nix file from a cargo rust project.
    help           Prints this message or the help of the given subcommand(s)

[nix-shell:~/repos/crate2nix]$ crate2nix "generate" "-f" "sample_projects/with_problematic_crates/Cargo.toml" "-o" "sample_projects/with_problematic_crates/Cargo.nix"
Generated sample_projects/with_problematic_crates/Cargo.nix successfully.

[nix-shell:~/repos/crate2nix]$ git diff -- sample_projects/with_problematic_crates/Cargo.nix | grep libPath
-        libPath = "cloudabi.rs";
-        libPath = "lib.rs";
-        libPath = "lib.rs";
-        libPath = "lib.rs";
-        libPath = "lib.rs";
-        libPath = "lib.rs";
-        libPath = "lib.rs";
-        libPath = "index_tests.rs";
-        libPath = "lib.rs";
-        libPath = "lib.rs";
-        libPath = "lib.rs";
-        libPath = "lib.rs";
-        libPath = "lib.rs";
-        libPath = "lib.rs";
-        libPath = "lib.rs";
-        libPath = "lib.rs";
-        libPath = "lib.rs";
-        libPath = "src/untrusted.rs";

[nix-shell:~/repos/crate2nix]$ 

``` 

The Cargo.nix file I generated: https://github.com/nlewo/crate2nix/commit/047ae1d4592c4001ab3accc51c469c5015c48601#diff-d44232a1e2e6e2b12c8e1ef2226078bc

Did I miss something or is it an real issue?

**Comment by kolloch** [comment]
Hmm, good question.

So, unfortunately, the `cargo metadata` command generates "opaque package IDs" which include local directory paths (see known issues in README). So these changes are expected.

The rest are not. Especially the libPath = "lib.rs" things should not be added since e2a0cc6abf22021fb13862783cfa9f5266f162a3, I guess?

In general, some of the changes could be explained by a `cargo update` but I did not see changes in the `Cargo.lock` file. I would hope that `cargo` produces reproducible output for `cargo metadata` with a given lockfile (except the packe ID problem).

**Comment by kolloch** [comment]
Any ideas how to follow up on this?

**Comment by kolloch** [comment]
Maybe you can try executing the "./regenerate_cargo_nix.sh"
