### ISSUE TITLE
target.'cfg(test)'.dependencies - unknown target `test`

### ISSUE THREAD

**Issue by andir** [kolloch/crate2nix#43]
With the following in `Cargo.toml`
```
[target.'cfg(test)'.dependencies]
tracing = { version = "0.1.5", features = ["log"] }
```
https://github.com/tokio-rs/tokio/blob/5efe31f2ed3c797e8055306a05faa3d7e786e7b6/tokio-net/Cargo.toml#L102

Crate2 nix creates  statement like `target."test"` but the that target isn't defined anywhere.

```
$ nix-build Cargo.nix -A rootCrate
error: attribute 'test' missing, at crate2nix-issues/cfg-test/Cargo.nix:89:22
(use '--show-trace' to show detailed location information)
```

I created a minimal test project at https://github.com/andir/crate2nix-issues/tree/d1e6ef9f7d1ea59a0286ee040015ba671511cb05/cfg-test

**Comment by kolloch** [comment]
Thank you very much for the example! I included it as a regression test.
