### ISSUE TITLE
Publish to a Binary Cache

### ISSUE THREAD

**Issue by vbrandl** [kolloch/crate2nix#44]
Building `crate2nix` can take really long. It would be cool, to offer a binary cache from which users can pull the precompiled nix package.

If you are OK with using GitHub Actions instead of Travis for your CI, you could use the cachix action to build an publish the package to a binary cache: https://github.com/cachix/cachix-action

**Comment by kolloch** [comment]
@vbrandl Thank you for the suggestion! My travis setup was horrible. I try this out currently....

**Comment by kolloch** [comment]
Thank you for the suggestion. The github action results in a build now. But the caching doesn't seem to work since it is still rebuilding everything from scratch. If you have an idea on how to change that, please let me know!

**Comment by vbrandl** [comment]
I'm not sure (never used the action before, I just thought, it might work)

Maybe you need to build `default.nix` instead of `tests.nix` for the caching to work and run the tests in a separate step? Just spitballing here...

**Comment by andir** [comment]
I think one of the problems with the current cachix approach in the GitHub action is that it isn't caching intermediate results aka all the dependencies of crate2nix.

Ideally we would be able to use the post-build-hook together with cachix. That would ensure all the build results get uploaded to the binary cache.

**Comment by kolloch** [comment]
I implemented to improvements so I'll close it now:

* In `run_tests.sh`, I also include a `cachix push` on my machine so that everything that I push to the github repo is usually prebuilt.
* I updated the version of the cachix hook so that this uses a post-build-hook now.
