### ISSUE TITLE
Dependencies enabled by features don't appear to work

### ISSUE THREAD

**Issue by VShell** [kolloch/crate2nix#65]
I'm trying to package Plume with SQLite for NixOS. I'm using the master branch of crate2nix. This involves disabling the default features and enabling a "sqlite" feature when building. Unfortunately, I get this when I override rootFeatures to be `[ "sqlite" ]`:

```
Building src/lib.rs (diesel)
Running rustc --crate-name diesel src/lib.rs --out-dir target/lib --emit=dep-info,link -L dependency=target/deps --cap-lints allow -C opt-level=3 -C codegen-units=2 --extern byteorder=/nix/store/xqnw4v9hx0zs6l2zl8y5m2dh7zd89pk1-rust_byteorder-1.3.1-lib/lib/libbyteorder-87d2e6ee33.rlib --extern chrono=/nix/store/3n27wrv96bid2sqd2h16izjc9l407ql1-rust_chrono-0.4.7-lib/lib/libchrono-f10bc22457.rlib --extern diesel_derives=/nix/store/avdwdilbck1264zzr8n589r3azn5b74p-rust_diesel_derives-1.4.0-lib/lib/libdiesel_derives-5ff800f449.so --extern r2d2=/nix/store/yfgzfik6ap7wrja09vh6wjlj678avlq8-rust_r2d2-0.8.4-lib/lib/libr2d2-f2ff8db6b6.rlib --cfg feature="32-column-tables" --cfg feature="chrono" --cfg feature="default" --cfg feature="diesel_derives/sqlite" --cfg feature="libsqlite3-sys" --cfg feature="r2d2" --cfg feature="sqlite" --cfg feature="with-deprecated" --edition 2015 -C metadata=7365896b5e -C extra-filename=-7365896b5e --crate-type lib --color always
error[E0463]: can't find crate for `ffi`
 --> src/sqlite/connection/mod.rs:1:1
  |
1 | extern crate libsqlite3_sys as ffi;
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate

error: aborting due to previous error
```

There is no reference to libsqlite3_sys in my Cargo.nix, however there is a reference in Cargo.lock. Any ideas?

**Comment by VShell** [comment]
Changing the Cargo.toml to set the default feature as "sqlite" results in libsqlite3-sys being included in the Cargo.nix, so it seems that the dependency resolution algorithm doesn't see crates that are only enabled by non-default features.

**Comment by kolloch** [comment]
Thank you very much for the report! that is unexpected and a bug.

Did you use the version from master? It would be helpful if you could provide an example that I could then also include in the regression tests.
