### ISSUE TITLE
not sure how to build protoc-rust-grpc

### ISSUE THREAD

**Issue by bbigras** [kolloch/crate2nix#66]
If I understand correctly I need to override `buildInputs` for the right crate. I think `protoc` is the one calling `protoc --version` ([here](https://github.com/stepancheg/rust-protobuf/blob/9d81264745951cb9491179be4f9a50a8bc1ce951/protoc/src/lib.rs#L292)). Does `buildInputs` add the bin to the `PATH`?

$ rg proto Cargo.lock  | rg name
name = "protobuf"
name = "protobuf-codegen"
name = "protoc"
name = "protoc-rust"
name = "protoc-rust-grpc"
name = "test-proto" // my crate

deps
```toml
[build-dependencies]
protoc-rust-grpc = "0.6"
```

build.rs
```rust

fn main() {
    protoc_rust_grpc::run(protoc_rust_grpc::Args {
        out_dir: "src",
        includes: &[],
        input: &["helloworld.proto"],
        rust_protobuf: true,
        ..Default::default()
    })
    .expect("protoc-rust-grpc");
}
```

helloworld.proto
```proto
syntax = "proto3";

package something;
```

log
```
Running rustc --crate-name build_script_build build.rs --crate-type bin -C opt-level=3 -C codegen-units=4 --edition 2018 --cfg feature="default" --out-dir target/build/test-proto --emit=dep-info,link -L dependency=target/buildDeps --extern protoc_rust_grpc=/nix/store/f2q18n4d63jxrlj5s41ivgzz3ql88nn7-rust_protoc-rust-grpc-0.6.2-lib/lib/libprotoc_rust_grpc-57fc54afe7.rlib --cap-lints allow --color always
thread 'main' panicked at 'protoc version: Custom { kind: NotFound, error: "failed to spawn `\"protoc\" \"--version\"`: No such file or directory (os error 2)" }', src/libcore/result.rs:1165:5
```

```nix
with (import <nixpkgs> {});

let
  myCrateBase = callPackage ./Cargo.nix {};
  myCrate = myCrateBase.rootCrate.build.override {
    crateOverrides = defaultCrateOverrides // {
      protoc = attrs: {
        buildInputs = [
          protobuf
        ];
      };
    };
  };
in
myCrate
```

**Comment by andir** [comment]
Try setting `PROTOC="${protobuf}/bin/protoc";` in your actual crates override. e.g:

```
with (import <nixpkgs> {});

let
  myCrateBase = callPackage ./Cargo.nix {};
  myCrate = myCrateBase.rootCrate.build.override {
    crateOverrides = defaultCrateOverrides // {
      myCrate = attrs: {
        PROTOC="${protobuf}/bin/protoc";
      };
    };
  };
in
myCrate
```
I have a few cases where `prost-build` is being used to build the protobuf files and setting `PROTOC` works there.

**Comment by bbigras** [comment]
It didn't seem to work.

One weird thing is that I also tried to set `PROTOC = "${protobuf324}/bin/protoc";` and it didn't whine except for the same error I had before. Is it being evaluated?

I created a repo if you want to test https://github.com/bbigras/test-proto

**Comment by danieldk** [comment]
> Try setting `PROTOC="${protobuf}/bin/protoc";` in your actual crates override. e.g:

I don't think that currently works. As far as I can see, `crateOverrides` are actually never passed through to `buildRustCrate`. However, if you modify the generated `Cargo.nix` with:

```diff
--- Cargo.nix.orig	2020-01-24 09:06:08.164919469 +0100
+++ Cargo.nix	2020-01-24 09:25:19.662569038 +0100
@@ -1293,7 +1293,8 @@
               url = "https://crates.io/api/v1/crates/${crateConfig.crateName}/${crateConfig.version}/download";
               sha256 = crateConfig.sha256;
             });
-            inherit features dependencies buildDependencies crateRenames;
+
+            inherit crateOverrides features dependencies buildDependencies crateRenames;
           });
     in builtByPackageId;
```

Building will fail with

```
Error: cannot coerce a set to a string, at /nix/store/xs747j6hnlyszg75qf4j7qpmascnjkkh-source/pkgs/build-support/rust/build-rust-crate/default.nix:93:5
```

The only thing that seems to work is if you provide a `buildRustCrate` to as an argument to `Cargo.nix` as in this test:

https://github.com/kolloch/crate2nix/blob/master/sample_projects/bin_with_git_submodule_dep/default.nix

**Comment by bbigras** [comment]
It works. Thanks @danieldk !
