### ISSUE TITLE
Consider making `--all-features` a default

### ISSUE THREAD

**Issue by nagisa** [kolloch/crate2nix#88]
Without this using `features = [...]` overrides to selectively enable features will not work right because the generated `Cargo.nix` will not have the relevant dependency information available for optional dependencies.

With recent improvements in prefetching (crate2nix no longer downloads every dependency crate when generating `Cargo.nix`) I think making `--all-features` a default is a very sensible UX improvement.

**Comment by kolloch** [comment]
Good suggestion!
